# Base configs
baseurl: "nnsriram97.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Sriram Narayanan"
subtitle: "See the world through my eyes!"
author: "Sriram Narayanan"
header:
 title: "Photography"
 subtitle: "by Sriram"
footer:
 name: "Hey there! I'm Sriram"
 bio: "I'm a PhD student at Carnegie Mellon University specializing in computer vision. My passion for creating compelling visuals in academic settings naturally extends to photography. I’m drawn to photography because I love the challenge of capturing moments and the creativity involved in editing them to highlight their beauty."
 github: ""
web_design: "Ram Patra"
social_urls:
  twitter: "https://www.twitter.com/nnsriram97"
  linkedin: "https://www.linkedin.com/in/sriram-narayanan-777a0010b/"
  github: "https://www.github.com/nnsriram97"
# mini_magick:
#     thumbnail:
#         source: ./images/fulls # source directory - change this to whatever you want
#         destination: ./images/thumbs/ # generated destination directory
#         resize: "852x480" # standard imagemagick options - you can chain multiple commands
#         gravity: "center"
#         extent: "852x480"
