# Base configs
baseurl: 
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Sriram Narayanan"
subtitle: "See the world through my eyes!"
author: "Sriram Narayanan"
header:
 title: "Photography"
 subtitle: "by Sriram"
footer:
 name: "Hey there, my name is Sriram"
 bio: "I am a PhD student at CMU. I work on computer vision and imaging in my research which got me excited to explore photography."
 github: ""
web_design: "Ram Patra"
social_urls:
  twitter: "https://www.twitter.com/nnsriram97"
  linkedin: "https://www.linkedin.com/in/sriram-narayanan-777a0010b/"
  github: "https://www.github.com/nnsriram97"
# mini_magick:
#     thumbnail:
#         source: ./images/fulls # source directory - change this to whatever you want
#         destination: ./images/thumbs/ # generated destination directory
#         resize: "852x480" # standard imagemagick options - you can chain multiple commands
#         gravity: "center"
#         extent: "852x480"
