# Base configs
baseurl: 
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Long Giang Vu"
subtitle: "See the world through my eyes!"
author: "Long Giang Vu"
header:
 title: "Photography"
 subtitle: "by Long-Giang"
footer:
 name: "Hey there! I'm Long Giang (Leo)"
 bio: "I'm a Masters student at University of California, San Diego specializing in computer science."
 github: ""
web_design: "Ram Patra"
social_urls:
  twitter: "https://x.com/leovulong"
  linkedin: "https://www.linkedin.com/in/long-giang-vu-735421174/"
  github: "https://github.com/ginlov"
# mini_magick:
#     thumbnail:
#         source: ./images/fulls # source directory - change this to whatever you want
#         destination: ./images/thumbs/ # generated destination directory
#         resize: "852x480" # standard imagemagick options - you can chain multiple commands
#         gravity: "center"
#         extent: "852x480"
